apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb
  namespace: mongodb
spec:
  capacity:
    storage: 80Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/supermap/mongodb/mongodb

