apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-harbor-registry
  namespace: harbor
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "glusterfs-gvr0"
    path: "gvr0/harbor-harbor-registry"
    readOnly: false
