kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfs
  namespace: nfs2x
  annotations:
    volume.beta.kubernetes.io/storage-class: "openthings-nfs"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
