apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-data-harbor-harbor-database-0
  namespace: harbor
spec:
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "glusterfs-gvzr00"
    path: "gvzr00"
    readOnly: false
