apiVersion: v1
kind: PersistentVolume
metadata:
  name: claim-supermap
  namespace: jupyter
spec:
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "glusterfs-gvzr00"
    path: "gvzr00/jupyterhub/claim-supermap"
    readOnly: false
