kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pvc-nfs2x
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs2x"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
