apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-gitlab-ce-etc
  namespace: gitlab
spec:
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "glusterfs-gvzr00"
    path: "gvzr00/gitlab/gitlab-gitlab-ce-etc"
    readOnly: false
