apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-harbor-jobservice
  namespace: harbor
spec:
  capacity:
    storage: 80Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "glusterfs-gvzr00"
    path: "gvzr00/harbor/harbor-harbor-jobservice"
    readOnly: false
