apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-gvz01
  namespace: glusterfs
subsets:
- addresses:
  - ip: 10.1.1.201
  - ip: 10.1.1.202
  - ip: 10.1.1.203
  ports:
  - port: 10001
    protocol: TCP

