apiVersion: v1
kind: PersistentVolume
metadata:
  name: glusterfs-gvz01-pv00
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "glusterfs-gvz01"
    path: "gvz01"
    readOnly: false
