apiVersion: v1
kind: PersistentVolume
metadata:
  name: glusterfs-gvz00-pv00
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "glusterfs-gvz00"
    path: "gvz00"
    readOnly: false
