apiVersion: v1
kind: PersistentVolume
metadata:
  name: glusterfs-gvx-pv00
spec:
  capacity:
    storage: 80Gi
  accessModes:
    - ReadWriteMany
  glusterfs:
    endpoints: "glusterfs-gvx"
    path: "gvx"
    readOnly: false
