kind: ConfigMap
apiVersion: v1
metadata:
  name: imanager-weixin-config
data:
  weixin.token: QMWCkr9nXZ
  weixin.corp.id: ww87015933668aaa18
  weixin.encoding.aes.key: nKc3vVipxbkcB4iOHc9uhLVC5bO5slOhTAfMueooK7h
---
apiVersion: v1
kind: Service
metadata:
  name: imanager-weixin-hook
  labels:
    type: imanager
    kind: imanager-base
spec:
  ports:
    - port: 8970
      targetPort: 8970
      nodePort: 31112
  selector:
    app: imanager-weixin-hook
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: imanager-weixin-hook
    type: imanager
    kind: imanager-base
  name: imanager-weixin-hook
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: imanager-weixin-hook
    spec:
      containers:
        - env:
          - name: IMANAGER_API_URL
            value: http://imanager-dashboard-backend:8980/imanager/dashboard/web/api
          - name: TOKEN
            valueFrom:
              configMapKeyRef:
                 name: imanager-weixin-config
                 key: weixin.token
          - name: CORP_ID
            valueFrom:
              configMapKeyRef:
                 name: imanager-weixin-config
                 key: weixin.corp.id
          - name: ENCODING_AES_KEY
            valueFrom:
              configMapKeyRef:
                 name: imanager-weixin-config
                 key: weixin.encoding.aes.key
          image: registry.cn-beijing.aliyuncs.com/supermap/imanager_weixin_hook
          name: imanager-weixin-hook
          imagePullPolicy: Always
          ports:
           - containerPort: 8970
          readinessProbe:
              tcpSocket:
                port: 8970
              initialDelaySeconds: 5
              periodSeconds: 2
      restartPolicy: Always
