apiVersion: v1
kind: Service
metadata:
  name: nfs-server-base
  labels:
    kind: imanager-base
spec:
  clusterIP: 10.111.11.111
  ports:
    - port: 2049
      targetPort: 2049
  selector:
    app: nfs-server-base
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: nfs-server-base
    kind: imanager-base
  name: nfs-server-base
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: nfs-server-base
    spec:
      nodeName: node1.domain
      containers:
        - image: registry.cn-beijing.aliyuncs.com/supermap/nfs-data
          name: nfs-server-base
          imagePullPolicy: IfNotPresent
          ports:
           - containerPort: 2049
          securityContext:
            privileged: true
          volumeMounts:
          - mountPath: /mnt/data
            name: nfs-data-volume
      volumes:
      - name: nfs-data-volume
        hostPath: 
            path: /var/lib/docker/nfsData
      tolerations: 
        - key: node-role.kubernetes.io/node1
          operator: Exists
          effect: NoSchedule
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    kind: imanager-base
  name: pv-nfs-imanager
spec:
  storageClassName: pv-nfs-imanager
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.111.11.111
    path: "/imanager/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    kind: imanager-base
  name: pv-nfs-mysql
spec:
  storageClassName: pv-nfs-mysql
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.111.11.111
    path: "/mysql/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    kind: imanager-base
  name: pv-nfs-elasticsearch
spec:
  storageClassName: pv-nfs-elasticsearch
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.111.11.111
    path: "/elasticsearch/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    kind: imanager-base
  name: pv-nfs-kibana
spec:
  storageClassName: pv-nfs-kibana
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.111.11.111
    path: "/kibana/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    kind: imanager-base
  name: pv-nfs-prometheus
spec:
  storageClassName: pv-nfs-prometheus
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.111.11.111
    path: "/prometheus/data"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    kind: imanager-base
  name: pv-nfs-grafana
spec:
  storageClassName: pv-nfs-grafana
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.111.11.111
    path: "/grafana/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    kind: imanager-base
  name: pvc-nfs-imanager
spec:
  storageClassName: pv-nfs-imanager
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    kind: imanager-base
  name: pvc-nfs-mysql
spec:
  storageClassName: pv-nfs-mysql
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    kind: imanager-base
  name: pvc-nfs-elasticsearch
spec:
  storageClassName: pv-nfs-elasticsearch
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    kind: imanager-base
  name: pvc-nfs-kibana
spec:
  storageClassName: pv-nfs-kibana
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    kind: imanager-base
  name: pvc-nfs-prometheus
spec:
  storageClassName: pv-nfs-prometheus
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    kind: imanager-base
  name: pvc-nfs-grafana
spec:
  storageClassName: pv-nfs-grafana
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
