apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-harbor-registry
  namespace: harbor
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/supermap/gvr0/harbor-harbor-registry
