apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-harbor-chartmuseum
  namespace: harbor
spec:
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /home/supermap/harbor/harbor-harbor-chartmuseum
