apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-data-harbor-harbor-database-0
  namespace: harbor
spec:
  capacity:
    storage: 16Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /gvzr00/harbor/database-data-harbor-harbor-database-0
    server: 10.1.1.202

