apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-harbor-registry
  namespace: harbor
spec:
  capacity:
    storage: 80Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /gvzr00/harbor/harbor-harbor-registry
    server: 10.1.1.202

