apiVersion: v1
kind: Pod
metadata:
  name: gpu-digits
spec:
  nodeName: podc01
  containers:
    - name: digits-container
      image: nvidia/digits:6.0
      resources:
        limits:
          nvidia.com/gpu: 1 # requesting 1 GPUs
